# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.31

# Default target executed when no arguments are given to make.
default_target: all
.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:

#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:

# Disable VCS-based implicit rules.
% : %,v

# Disable VCS-based implicit rules.
% : RCS/%

# Disable VCS-based implicit rules.
% : RCS/%,v

# Disable VCS-based implicit rules.
% : SCCS/s.%

# Disable VCS-based implicit rules.
% : s.%

.SUFFIXES: .hpux_make_needs_suffix_list

# Command-line flag to silence nested $(MAKE).
$(VERBOSE)MAKESILENT = -s

#Suppress display of executed commands.
$(VERBOSE).SILENT:

# A target that is always out of date.
cmake_force:
.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /opt/homebrew/bin/cmake

# The command to remove a file.
RM = /opt/homebrew/bin/cmake -E rm -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /Users/vchele/CLionProjects/Lab2_v1

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /Users/vchele/CLionProjects/Lab2_v1

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Running CMake cache editor..."
	/opt/homebrew/bin/ccmake -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache
.PHONY : edit_cache/fast

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Running CMake to regenerate build system..."
	/opt/homebrew/bin/cmake --regenerate-during-build -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache
.PHONY : rebuild_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /Users/vchele/CLionProjects/Lab2_v1/CMakeFiles /Users/vchele/CLionProjects/Lab2_v1//CMakeFiles/progress.marks
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /Users/vchele/CLionProjects/Lab2_v1/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean
.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named Lab2_v1

# Build rule for target.
Lab2_v1: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 Lab2_v1
.PHONY : Lab2_v1

# fast build rule for target.
Lab2_v1/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Lab2_v1.dir/build.make CMakeFiles/Lab2_v1.dir/build
.PHONY : Lab2_v1/fast

MyList.o: MyList.c.o
.PHONY : MyList.o

# target to build an object file
MyList.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Lab2_v1.dir/build.make CMakeFiles/Lab2_v1.dir/MyList.c.o
.PHONY : MyList.c.o

MyList.i: MyList.c.i
.PHONY : MyList.i

# target to preprocess a source file
MyList.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Lab2_v1.dir/build.make CMakeFiles/Lab2_v1.dir/MyList.c.i
.PHONY : MyList.c.i

MyList.s: MyList.c.s
.PHONY : MyList.s

# target to generate assembly for a file
MyList.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Lab2_v1.dir/build.make CMakeFiles/Lab2_v1.dir/MyList.c.s
.PHONY : MyList.c.s

main.o: main.c.o
.PHONY : main.o

# target to build an object file
main.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Lab2_v1.dir/build.make CMakeFiles/Lab2_v1.dir/main.c.o
.PHONY : main.c.o

main.i: main.c.i
.PHONY : main.i

# target to preprocess a source file
main.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Lab2_v1.dir/build.make CMakeFiles/Lab2_v1.dir/main.c.i
.PHONY : main.c.i

main.s: main.c.s
.PHONY : main.s

# target to generate assembly for a file
main.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Lab2_v1.dir/build.make CMakeFiles/Lab2_v1.dir/main.c.s
.PHONY : main.c.s

mysort.o: mysort.c.o
.PHONY : mysort.o

# target to build an object file
mysort.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Lab2_v1.dir/build.make CMakeFiles/Lab2_v1.dir/mysort.c.o
.PHONY : mysort.c.o

mysort.i: mysort.c.i
.PHONY : mysort.i

# target to preprocess a source file
mysort.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Lab2_v1.dir/build.make CMakeFiles/Lab2_v1.dir/mysort.c.i
.PHONY : mysort.c.i

mysort.s: mysort.c.s
.PHONY : mysort.s

# target to generate assembly for a file
mysort.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Lab2_v1.dir/build.make CMakeFiles/Lab2_v1.dir/mysort.c.s
.PHONY : mysort.c.s

pet.o: pet.c.o
.PHONY : pet.o

# target to build an object file
pet.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Lab2_v1.dir/build.make CMakeFiles/Lab2_v1.dir/pet.c.o
.PHONY : pet.c.o

pet.i: pet.c.i
.PHONY : pet.i

# target to preprocess a source file
pet.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Lab2_v1.dir/build.make CMakeFiles/Lab2_v1.dir/pet.c.i
.PHONY : pet.c.i

pet.s: pet.c.s
.PHONY : pet.s

# target to generate assembly for a file
pet.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Lab2_v1.dir/build.make CMakeFiles/Lab2_v1.dir/pet.c.s
.PHONY : pet.c.s

petstoreservice.o: petstoreservice.c.o
.PHONY : petstoreservice.o

# target to build an object file
petstoreservice.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Lab2_v1.dir/build.make CMakeFiles/Lab2_v1.dir/petstoreservice.c.o
.PHONY : petstoreservice.c.o

petstoreservice.i: petstoreservice.c.i
.PHONY : petstoreservice.i

# target to preprocess a source file
petstoreservice.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Lab2_v1.dir/build.make CMakeFiles/Lab2_v1.dir/petstoreservice.c.i
.PHONY : petstoreservice.c.i

petstoreservice.s: petstoreservice.c.s
.PHONY : petstoreservice.s

# target to generate assembly for a file
petstoreservice.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Lab2_v1.dir/build.make CMakeFiles/Lab2_v1.dir/petstoreservice.c.s
.PHONY : petstoreservice.c.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... edit_cache"
	@echo "... rebuild_cache"
	@echo "... Lab2_v1"
	@echo "... MyList.o"
	@echo "... MyList.i"
	@echo "... MyList.s"
	@echo "... main.o"
	@echo "... main.i"
	@echo "... main.s"
	@echo "... mysort.o"
	@echo "... mysort.i"
	@echo "... mysort.s"
	@echo "... pet.o"
	@echo "... pet.i"
	@echo "... pet.s"
	@echo "... petstoreservice.o"
	@echo "... petstoreservice.i"
	@echo "... petstoreservice.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

